"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")

DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')]
# ALLOWED_HOSTS = ['www.tempest.today', 'tempest.today']

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.apple",
    "core",
]

MIDDLEWARE = [
    "core.middleware.BlockedIPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.ClientPlatformMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', '/static/')

# This tells Django to put collected files in a folder named 'staticfiles' in your project root
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security settings
# SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Add "www." in production only; keeps local/LAN IP testing (e.g. phone on Wi-Fi) working.
PREPEND_WWW = not DEBUG
# SESSION_COOKIE_SECURE = os.environ.get('DJANGO_COOKIE_SECURE', 'True') == 'True'
# CSRF_COOKIE_SECURE = os.environ.get('DJANGO_COOKIE_SECURE', 'True') == 'True'
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Make CSRF token last longer (default is session length)
CSRF_COOKIE_AGE = 31449600  # 1 year in seconds

# Or make session last longer
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds (default is 2 weeks already)

# Cache configuration - use local memory cache (good for single-process apps)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-weather-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000  # Store up to 1000 location caches
        }
    }
}

LOCATIONIQ_API_KEY = os.getenv('LOCATIONIQ_API_KEY')
AIRNOW_API_KEY = os.getenv('AIRNOW_API_KEY')

# ---------------------------------------------------------------------------
# Accounts (django-allauth) — accounts are only ever created on demand, the
# first time a free user tries to unlock a premium feature. Nothing here
# creates or requires an account for ordinary anonymous browsing.
# ---------------------------------------------------------------------------
SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
# Email ownership is already proven by our own magic link, and by Google/Apple
# themselves for social logins — no separate verification email needed.
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_RATE_LIMITS = {
    # Applies to allauth's own views; our hand-rolled magic-link endpoints
    # rate-limit separately (see core/views_auth.py).
    "login_failed": "10/m/ip,20/5m/ip",
}

# Skip the "you're about to sign in with Google" intermediate page — the
# WebView is already inside our own app chrome, no need for a confirm step.
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # link social login to an existing account by verified email
SOCIALACCOUNT_STORE_TOKENS = False

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APPS": [
            {
                "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
                "secret": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", ""),
                "key": "",
            },
        ],
    },
    "apple": {
        "APPS": [
            {
                # "Services ID" identifier, e.g. today.tempest.web-signin
                "client_id": os.environ.get("APPLE_OAUTH_CLIENT_ID", ""),
                # NOTE: allauth's field names for Apple are non-obvious —
                # "secret" holds the Sign-in-with-Apple Key ID, and "key"
                # holds your Apple Developer Team ID. Neither is a secret
                # you're given by Apple; allauth builds the actual JWT
                # client secret itself from these plus the private key
                # below, refreshed automatically.
                "secret": os.environ.get("APPLE_OAUTH_KEY_ID", ""),
                "key": os.environ.get("APPLE_TEAM_ID", ""),
                "settings": {
                    "certificate_key": os.environ.get("APPLE_OAUTH_PRIVATE_KEY", "").replace("\\n", "\n"),
                },
            },
        ],
    },
}

# Where to send the browser after a successful login (social or magic link)
# when no explicit ?next= was given.
LOGIN_REDIRECT_URL = "/"

# ---------------------------------------------------------------------------
# Outgoing email (magic links). Any standard SMTP provider works — see the
# setup notes for recommended options.
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Tempest Today <noreply@tempest.today>")

# Base URL used to build the magic-link email (no trailing slash), e.g.
# "https://www.tempest.today". Falls back to DEBUG-friendly localhost.
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "http://localhost:8000")

# ---------------------------------------------------------------------------
# In-app purchase verification (Apple App Store / Google Play)
# ---------------------------------------------------------------------------
APPLE_BUNDLE_ID = os.environ.get("APPLE_BUNDLE_ID", "")
APPLE_APP_APPLE_ID = os.environ.get("APPLE_APP_APPLE_ID")  # numeric App Store Connect app ID
APPLE_APP_APPLE_ID = int(APPLE_APP_APPLE_ID) if APPLE_APP_APPLE_ID else None
APPLE_IAP_ENVIRONMENT = os.environ.get("APPLE_IAP_ENVIRONMENT", "Production")  # or "Sandbox"
# Directory of Apple's public root CA .cer files (download once, see setup notes).
APPLE_ROOT_CERTS_DIR = os.environ.get("APPLE_ROOT_CERTS_DIR", str(BASE_DIR / "apple_root_certs"))

GOOGLE_PLAY_PACKAGE_NAME = os.environ.get("GOOGLE_PLAY_PACKAGE_NAME", "")
# Path to the Google Cloud service account JSON with Play Console API access.
GOOGLE_PLAY_SERVICE_ACCOUNT_PATH = os.environ.get("GOOGLE_PLAY_SERVICE_ACCOUNT_PATH", "")
# Expected audience/service-account-email for verifying Pub/Sub push OIDC tokens.
GOOGLE_PUBSUB_AUDIENCE = os.environ.get("GOOGLE_PUBSUB_AUDIENCE", "")
GOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL = os.environ.get("GOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL", "")
